// Auto-generated by Xcode Build Phase. Do not edit.
// Values below are placeholders overwritten at build time with git info.
enum BuildInfo {
    static let gitCommitHash = "unknown"
    static let gitCommitHashFull = "unknown"
    static let version = "0.0.0"
}
